<?php
/**
 * Copyright (c) Right Submission, LLC 2016-2018. All Rights Reserved.
 * All information contained herein is, and remains the property of Right Submission, LLC. the intellectual and technical
 * concepts contained herein are proprietary to Right Submission, LLC. Dissemination of this information or reproduction
 * of this material is strictly forbidden unless prior written permission is obtained from Right Submission, LLC.
 **/


namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectExportRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileUploadRepository extends EntityRepository {



}
